### ISSUE TITLE
use common .on()/.off() method naming

### ISSUE THREAD

**Issue by smhg** [eiriklv/event-clock#1]
Hi! I was looking at using this library in a project, but I have a few suggestions.
I'll mention them as separate issues. Dismiss or comment on them as you feel appropriate.
Please accept my apologies for the upcoming flood :) I might even send in PR's.

I would love to hook into "clock" events in a traditional .on() / .off() style.
That would require renaming/aliasing .at() to .on() and adding .off().

**Comment by eiriklv** [comment]
I think this sounds like a good idea. This was just made quickly to accommodate some needs at the time. I wanted an event-emitter for the clock or arbitrary times/occurences basicly :-)
