### ISSUE TITLE
go easy on dependencies

### ISSUE THREAD

**Issue by smhg** [eiriklv/event-clock#3]
My goal is to use event-clock in the browser (through browserify).
This means less dependencies is better.
- Can **moment** be replaced by the native Date?
- Is **EventEmitter / util** really necessary?
- **async** isn't used?

As I mentioned in #1, these are just suggestions. And I'm happy to contribute should you agree that these are useful.

**Comment by eiriklv** [comment]
I'm not sure how you would do this without the event-emitter, as in another approach of mine (https://github.com/eiriklv/event-schedule) i basicly ended up re-implementing event-emitter myself :-P

The reason for using moment was to be able to use more "loose" formats for time, but I'm not sure if it's really necessary.

**Comment by smhg** [comment]
Released as [1.1.0](https://github.com/eiriklv/event-clock/releases/tag/v1.1.0).
