### ISSUE TITLE
release version 1.0.0

### ISSUE THREAD

**Issue by smhg** [eiriklv/event-clock#7]
@eiriklv I've finally found time to get this moving again.

What I've changed:
* Updated dependencies (as much as possible without introducing breaking changes) to remove all npm security warnings.
* Added ESLint-based linting and code formatting (Standard JS).
* Updated tests to stop 'ticking' after tests complete (for mocha >=4.x).
* Added version and publish scripts to always run linting and tests first.

I've also taken the liberty to tag this as a 1.0.0 release.
Would you be able to publish on npm?

After this, I'll create branches for the issues that I think might still be relevant.

Thank you!

**Comment by eiriklv** [comment]
'tis the season for such! Published it to npm 🎄🎅

**Comment by smhg** [comment]
Thank you! :fireworks:
