### ISSUE TITLE
release 1.1.0 and 1.2.0

### ISSUE THREAD

**Issue by smhg** [eiriklv/event-clock#8]
@eiriklv I've tagged 2 more [releases](https://github.com/eiriklv/event-clock/releases) which keep backward compatibility.

It would be great if you can also put them on npm with:
```bash
git checkout v1.1.0
npm publish

git checkout v1.2.0
npm publish
```
I've also set up a GitHub action (CI) to run tests on push. You might have received some messages about this.

Some possible future steps:

* Use modern JS syntax and drop old node support.
* Only start the clock when callbacks are registered and stop when all callbacks are removed.
* Handle objects that implement the [Iterator protocol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#The_iterator_protocol) and schedule them with `setTimeout` instead (related to #2 and #4).

This would however change things considerably.

**Comment by eiriklv** [comment]
Great work Sam 👍 I’ve checked npmjs.com - you should have access to publish to npm. Give it a try and report back.

- Eirik

**Comment by smhg** [comment]
That worked wonderfully! Thank you!
